name: smart_waste_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

flutter:
  generate: true
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0
  path_provider: ^2.0.14
  path: ^1.8.3
  speech_to_text: ^7.0.0
  intl: 0.19.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.2
  http: ^0.13.6
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
